- Gemfile
- Gemfile.lock
- app/models/customer.rb
- app/models/invoice.rb
- app/models/invoice_item.rb
- app/models/item.rb
- app/models/merchant.rb
- app/models/transaction.rb
- db/migrate/20240220215137_create_customers.rb
- db/migrate/20240220215523_create_invoices.rb
- db/migrate/20240220215615_create_merchants.rb
- db/migrate/20240220215701_create_items.rb
- db/migrate/20240220215839_create_transactions.rb
- db/migrate/20240220220145_create_invoice_items.rb
- db/schema.rb
- spec/factories/customers.rb
- spec/factories/invoice_items.rb
- spec/factories/invoices.rb
- spec/factories/items.rb
- spec/factories/merchants.rb
- spec/factories/transactions.rb
- spec/models/customer_spec.rb
- spec/models/invoice_item_spec.rb
- spec/models/invoice_spec.rb
- spec/models/item_spec.rb
- spec/models/merchant_spec.rb
- spec/models/transaction_spec.rb
This branch adds the following:
- Database schema and migration files to get everyone set with the same initial database structure
- Gemfile update for necessary gems
- Relationships and validations, including tests, for all models
- Space to create enum testing for all models with enums
> Database setup

- app/models/transaction.rb
- spec/models/invoice_spec.rb
- spec/models/transaction_spec.rb
- spec/rails_helper.rb
- Fix missing shoulda matchers code in rails helper
- Fix copy paste error in invoice spec
- Fix incorrect naming for enums in transaction model
> fix: Fix missing rails helper info

- Gemfile
- Gemfile.lock
- app/controllers/admin_controller.rb
- app/models/customer.rb
- app/models/invoice.rb
- app/views/admin/index.html.erb
- config/routes.rb
- spec/factories/customers.rb
- spec/factories/invoices.rb
- spec/factories/transactions.rb
- spec/features/admin/index_spec.rb
- spec/models/customer_spec.rb
- spec/models/invoice_spec.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
Together we added features for Admin Dashboard to display the correct header, links to admin merchants and invoices indexes, and the top 5 customers with the number of successful transactions conducted by them.
For this we settled up some factory files for testing purposes and also two methods in Customer model with the corresponding tests.
All tests passing.
Note: we just noticed we need to add the setup for SimpleCov.
closes #27 
closes #24 
closes #21
> Feat admin dashboard

- lib/tasks/import.rake
Together with a mentor we added the DB Rake Setup :)
> Setup the rake functionality

- app/controllers/merchants_controller.rb
- app/views/merchants/index.html.erb
- config/routes.rb
- spec/factories/items.rb
- spec/factories/merchants.rb
- spec/features/merchants/index_spec.rb
Completed user story 1 and 2, still have some questions about the routing.
> Finish user story 1 and 2

- app/models/merchant.rb
- app/views/merchants/dashboard.html.erb
- spec/features/merchants/dashboard_spec.rb
> Finish user story 4

- spec/models/merchant_spec.rb
> add us-4 model test

- .gitignore
- app/controllers/admin/merchants_controller.rb
- app/views/admin/merchants/index.html.erb
- app/views/admin/merchants/show.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- spec/features/admin/merchants/edit_spec.rb
- spec/features/admin/merchants/index_spec.rb
- spec/features/admin/merchants/show_spec.rb
This branch:
-Solves user stories 24, 25, 26
- Updates the routes for the paths in admin merchants index, show, update and edit
- Updates admin merchants controller with actions update, edit with the flash message for information successfully updated.
- All tests passing.
> Admin merchants index

- app/controllers/merchant_items_controller.rb
- app/views/merchant_items/index.html.erb
- app/views/merchant_items/show.html.erb
- config/routes.rb
- spec/features/merchants/items/show_spec.rb
us-7. not 100% sure on the show method for it but I'm tired.
> finish us-7

- app/controllers/admin/merchants_controller.rb
- app/controllers/application_controller.rb
- spec/features/admin/merchants/edit_spec.rb
- spec/features/admin/merchants/new_spec.rb
This branch adds the testing and handling methods for sad path cases, supporting user stories 26 and 29.
> Admin merchants sad path

- spec/features/merchants/dashboard_spec.rb
- spec/features/merchants/items/show_spec.rb
- spec/models/merchant_spec.rb
> Us 5 refactor

- app/controllers/merchant_items_controller.rb
- app/views/merchant_items/edit.html.erb
- app/views/merchant_items/show.html.erb
- config/routes.rb
- spec/features/merchants/items/show_spec.rb
> Finish us 8

- app/controllers/merchant_items_controller.rb
- app/models/item.rb
- app/models/merchant.rb
- app/views/merchant_items/index.html.erb
- db/migrate/20240220215701_create_items.rb
- db/schema.rb
- spec/features/merchants/items/index_spec.rb
- spec/features/merchants/items/show_spec.rb
- spec/models/item_spec.rb
- spec/models/merchant_spec.rb
accidentally did this on us-9 but we did 10 and 12. still need to hit 11.
> finish us 10 and 12

- app/controllers/admin/invoices_controller.rb
- app/models/merchant.rb
- app/views/admin/invoices/index.html.erb
- app/views/admin/invoices/show.html.erb
- app/views/admin/merchants/index.html.erb
- config/routes.rb
- db/schema.rb
- spec/features/admin/invoices/index_spec.rb
- spec/features/admin/invoices/show_spec.rb
- spec/features/admin/merchants/index_spec.rb
- spec/models/merchant_spec.rb
This branch does the following:
- Adds model instance method #top_revenue_day to merchant model
- Adds ability to see each of the top five merchants best day based on successful invoice revenue, sorted by most recent highest sales, in admin merchants index page
- Adds admin invoice index page which shows all invoices currently in the system
- Adds admin invoice show page which shows invoice id, status, date created, and customer first and last name associated with the invoice
All tests passing
> Admin merchants top sell date

- app/controllers/merchant_items_controller.rb
- app/views/merchant_items/index.html.erb
- app/views/merchant_items/new.html.erb
- config/routes.rb
- spec/features/merchants/items/index_spec.rb
> Finish us 11

- app/models/item.rb
- app/views/merchant_items/index.html.erb
- spec/features/merchants/items/index_spec.rb
finished us-13. model method took some work but got it going.
> finish us-13

- app/views/merchant_invoices/show.html.erb
- spec/features/merchants/invoices/show_spec.rb
> Finish us 15

- app/models/item.rb
- app/views/merchant_invoices/show.html.erb
- spec/features/merchants/invoices/show_spec.rb
> finish us-16

- app/models/invoice.rb
- app/views/merchant_invoices/show.html.erb
- spec/features/merchants/invoices/show_spec.rb
- spec/models/invoice_spec.rb
- spec/models/item_spec.rb
Finish us 17 and some model methods
> Finish us 17 and some model methods

- spec/models/invoice_item_spec.rb
- spec/models/invoice_spec.rb
- spec/models/merchant_spec.rb
- spec/models/transaction_spec.rb
This branch adds tests for Enums in all models that include them
> Test: add enum tests for models

- app/views/admin/invoices/show.html.erb
- app/views/layouts/application.html.erb
- spec/features/admin/invoices/show_spec.rb
This branch formats items on this invoice section for Admin Invoice Show to get closer to requested wireframe.
> Add table settings for Admin invoice show view

- spec/models/item_spec.rb
> add enabled and disabled item tests

- app/models/invoice_item.rb
- app/models/item.rb
- app/models/merchant.rb
- app/models/transaction.rb
> removed commented out code

- app/views/welcome/index.html.erb
- spec/features/merchants/index_spec.rb
- spec/features/welcome/index_spec.rb
This branch adds the testing for untested views
> Test missing views

- app/models/customer.rb
- app/models/invoice_item.rb
- app/models/merchant.rb
- app/models/transaction.rb
- spec/models/merchant_spec.rb
Refactor the following active record methods to utilize our built in associations between models:
- top_five_merchants
- top_revenue_day
- top_five_customers
Removes some unnecessary comments in various places
> Active record refactor
